version: '3.4'

services:
  newslettersignup:
    image: newslettersignup
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
